global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:9000"]

  - job_name: "test-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["test-app:5000"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
